### PR TITLE
Add source .env file in template script

### PR DESCRIPTION
**Pull request by nbtm-sh**
feat(environment): Laying groundwork for prod/uat/dev environments

### CODE REVIEW

**Review by jscgh — APPROVED** [review]

**Review by keiran-rowell-unsw — APPROVED** [review]
Looks like a reasonable approach. Might want to consider a less generic ENVIRONMENT name to avoid accidental crash. 

Default to dev is great.

**Comment by nbtm-sh** [comment]
@keiran-rowell-unsw, it actually defaults to `prod`, should this be changed to `dev`?

**Comment by keiran-rowell-unsw** [comment]
> @keiran-rowell-unsw, it actually defaults to `prod`, should this be changed to `dev`?

I meant prod blah. Works well, brain failing

**Comment by nbtm-sh** [comment]
Lmao cheers 👍

**Pull request merged**
